name: millie
description: Convert big numbers to what's pleasant to see (an adorable, little girl, perhaps?)
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
